package be.howest.sooa.o4.gui;

import be.howest.sooa.o4.domain.Genre;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Hayk
 */
public class GenreDialog extends javax.swing.JDialog {

    private transient Genre genre;
    private final MainFrame frame;

    public GenreDialog(MainFrame frame) {
        this(frame, null);
    }

    public GenreDialog(MainFrame frame, Genre genre) {
        super(frame, true);
        initComponents();
        this.genre = genre;
        this.frame = frame;
        if (genre != null) {
            deleteButton.setEnabled(true);
            genreField.setText(genre.toString());
        }
        addListeners();
    }

    // <editor-fold defaultstate="collapsed" desc="Listeners">
    private void addListeners() {
        frame.addDialogKeyListener(this);
        addCancelButtonActionListener();
        addSaveButtonActionListener();
        if (genre != null) {
            addDeleteGenreButtonActionListener();
        }
        addFieldEnterKeyActionListeners();
    }

    private void addCancelButtonActionListener() {
        cancelButton.addActionListener((ActionEvent e) -> {
            setVisible(false);
            dispose();
        });
    }

    private void addSaveButtonActionListener() {
        saveButton.addActionListener((ActionEvent e) -> {
            String newGenre = genreField.getText().trim();
            if ("".equals(newGenre)) {
                showWarning();
            } else {
                saveGenre(newGenre);
            }
        });
    }

    private void showWarning() {
        String message = "Genre field may not be empty!";
        JOptionPane.showMessageDialog(this, message, "Warning",
                JOptionPane.WARNING_MESSAGE);
    }

    private void addDeleteGenreButtonActionListener() {
        deleteButton.addActionListener((ActionEvent e) -> {
            Object[] options = {"Do not delete", "Delete Genre"};
            int result = JOptionPane.showOptionDialog(this,
                    "Please, apply you want to delete the following genre:\n"
                    + genre,
                    "Delete genre?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);
            if (result == 1) {
                frame.deleteGenre(genre);
                setVisible(false);
                dispose();
            }
        });
    }

    private void addFieldEnterKeyActionListeners() {
        genreField.addActionListener((ActionEvent e) -> {
            saveButton.doClick();
        });
    }

    // </editor-fold>
    //
    // <editor-fold defaultstate="collapsed" desc="Data Manipulation">
    private void saveGenre(String newGenre) {
        if (genre == null) {
            buildGenre(newGenre);
            frame.saveGenre(genre);
        } else {
            updateGenre(genre, newGenre);
            frame.updateGenre(genre);
        }
        setVisible(false);
        dispose();
    }

    private void buildGenre(String newGenre) {
        genre = new Genre(newGenre);
        genre.setName(newGenre);
    }

    private void updateGenre(Genre genre, String newGenre) {
        genre.setName(newGenre);
    }

    // </editor-fold>
    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreLabel = new javax.swing.JLabel();
        genreField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(null);

        genreLabel.setText("Genre");

        saveButton.setText("Save Genre");

        cancelButton.setText("Do not save");

        deleteButton.setText("Delete Genre");
        deleteButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genreField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genreLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(deleteButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField genreField;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
